// Generated by Toolkit-Py[v0.16.8] Generator. Created at 2022-04-07 08:44:23.559895.

#ifndef DIGEST_AUTH_QT5__HTTP_CLIENT_AUTH_H
#define DIGEST_AUTH_QT5__HTTP_CLIENT_AUTH_H

#include <QByteArray>

typedef struct {
    QByteArray Username;
    QByteArray Password;
    QByteArray Method;
    QByteArray Uri;
    QByteArray Realm;
    QByteArray Nonce;
    QByteArray Cnonce;
    QByteArray Nc;
    QByteArray Qop;
    QByteArray Algorithm;
    QByteArray Response;
} Digest;

QByteArray getRandomHex(const int &length);

QString generateDigestAuthentication(Digest &digest);

#endif//DIGEST_AUTH_QT5__HTTP_CLIENT_AUTH_H
